### ISSUE TITLE
No room plugin settings in Wwise.

### ISSUE THREAD

**Issue by JeffBrilhante** [resonance-audio/resonance-audio-wwise-sdk#2] opened 2018-02-11 15:47 UTC
Hello,

I just downloaded Resonance and I am having a bit of trouble. When I import the plugin into wwise the room settings are blank but i can attach to plugin to the effects bus and mixer plugin. I know in the documentation it says you may need to configure the plugin, what file do I alter and lines to change? and how do I configure the plugin? Is there something I am missing that may make this easier? Is there a .json file that I can use to import from the launcher?

Thank you,
-Jeff

**Comment by anokta** [comment] 2018-02-20 21:41
Hey Jeff,

As already mentioned in the StackOverflow post, modifying the room properties for the room effects plugin is only allowed through the game engine integrations. Please [see the corresponding section in the Resonance Audio SDK for Wwise documentation](https://developers.google.com/resonance-audio/develop/wwise/game-engine-integration#room_effects_game_engine_integration) for further information.

Closing the issue as this is intended behavior, but please feel free to let us know in case you have any additional questions.

**Closed by anokta** 2018-02-20 21:41 UTC

**Comment by JeffBrilhante** [comment] 2018-02-21 05:03
Hello, 

Thank you for the response. I did have one more issue though. I now get these errors in Unity saying the plugin is not registered? Not sure how to get around this. If you could help me on this issue that would be amazing!  

![screen shot 2018-02-20 at 8 56 41 pm](https://user-images.githubusercontent.com/11791326/36463835-35c9ca00-1681-11e8-8e52-4435bf8438ac.png)

**Comment by EgilSandfeld** [comment] 2018-02-21 06:20
Did you make sure to add the plugin libraries into

Assets/Wwise/Deployment/Plugins 

into the corresponding platforms? I find they often need to be placed in the DSP folder if it'd present for the platform. You can find the libraries in the Resonance Audio zip under /SDK

**Comment by JeffBrilhante** [comment] 2018-02-21 08:14
I did have them implemented but I went ahead and replaced them and it worked!!! Thank you. Must have messed up originally somehow. Thank you for your help here and [here](https://stackoverflow.com/questions/48833080/wwise-resonance-audio-and-unity-integration-configure-wwise-resonance-audio-pl/48861863#48861863)
